SELECT
    CI.NAME AS CIDADE,
    C.NAME AS PAIS,
    C.CONTINENT AS CONTINENTE,
    CI.POPULATION AS POPULACAO,
    CASE
        WHEN CI.POPULATION > 5000000 THEN 'MEGACIDADE'
        WHEN CI.POPULATION >= 1000000 AND CI.POPULATION <= 5000000 THEN 'CIDADE GRANDE'
        WHEN CI.POPULATION >= 500000 AND CI.POPULATION < 1000000 THEN 'CIDADE MÉDIA'
        ELSE 'CIDADE PEQUENA'
    END AS CLASSIFICACAO_CIDADE
FROM CITY CI
INNER JOIN COUNTRY C
    ON CI.COUNTRYCODE = C.CODE
WHERE C.CONTINENT = 'EUROPE'
    AND CI.POPULATION > 100000
ORDER BY POPULACAO DESC
LIMIT 20;
