SELECT
	C1.CONTINENT AS CONTINENTE,
	COUNT(C1.CODE) AS QTD_PAISES,
	SUM(C1.POPULATION) AS POPULACAO_TOTAL
FROM COUNTRY C1
WHERE
	EXISTS (SELECT 1
			FROM COUNTRY C2
			WHERE C2.LIFEEXPECTANCY > 80
			AND C2.CONTINENT = C1.CONTINENT)
GROUP BY C1.CONTINENT
HAVING COUNT(C1.CODE) > 10
ORDER BY POPULACAO_TOTAL DESC;
