WITH PAISES_COM_MUITAS_CIDADES AS (
    SELECT
        COUNTRYCODE,
        COUNT(*) AS QTD_CIDADES
    FROM CITY
    GROUP BY COUNTRYCODE
    HAVING COUNT(*) > 10
)
SELECT
    C.CONTINENT AS CONTINENTE,
    COUNT(*) AS QTD_PAISES,
    SUM(C.POPULATION) AS POPULACAO_TOTAL,
    AVG(C.POPULATION) AS MEDIA_POPULACAO
FROM PAISES_COM_MUITAS_CIDADES PCMC
INNER JOIN COUNTRY C
    ON PCMC.COUNTRYCODE = C.CODE
GROUP BY C.CONTINENT
HAVING COUNT(*) > 2
ORDER BY POPULACAO_TOTAL DESC;
