SELECT
	C.NAME AS PAIS,
	C.CONTINENT AS CONTINENTE,
	C.POPULATION AS POPULACAO
FROM COUNTRY C
WHERE EXISTS
		(SELECT 1
		 FROM CITY CI
		 WHERE C.CODE = CI.COUNTRYCODE AND
			CI.POPULATION > 8000000)
ORDER BY POPULACAO DESC
LIMIT 10;
