WITH MEDIA_POPULACAO_CONTINENTE AS (
	SELECT
        AVG(POPULATION) AS MEDIA_POPULACAO,
        CONTINENT AS CONTINENTE
	FROM COUNTRY
    GROUP BY CONTINENT
)
SELECT
	C.NAME AS PAIS,
    C.CONTINENT AS CONTINENTE,
    C.POPULATION AS POPULACAO,
    MPC.MEDIA_POPULACAO AS MEDIA_POPULACAO
FROM COUNTRY C
INNER JOIN MEDIA_POPULACAO_CONTINENTE MPC
ON C.CONTINENT = MPC.CONTINENT
WHERE C.POPULATION > MPC.MEDIA_POPULACAO
ORDER BY C.POPULATION DESC
LIMIT 20;
