SELECT
    NAME AS PAIS,
    CONTINENT AS CONTINENTE,
    POPULATION AS POPULACAO,
    'PAIS ASIATICO POPULOSO' AS CATEGORIA_REGISTRO
FROM COUNTRY
WHERE CONTINENT = 'ASIA'
    AND POPULATION > 50000000

UNION

SELECT
    NAME AS PAIS,
    CONTINENT AS CONTINENTE,
    POPULATION AS POPULACAO,
    'PAIS EUROPEU POPULOSO' AS CATEGORIA_REGISTRO
FROM COUNTRY
WHERE CONTINENT = 'EUROPE'
    AND POPULATION > 30000000

UNION

SELECT
    NAME AS PAIS,
    CONTINENT AS CONTINENTE,
    POPULATION AS POPULACAO,
    'PAIS SUL-AMERICANO POPULOSO' AS CATEGORIA_REGISTRO
FROM COUNTRY
WHERE CONTINENT = 'SOUTH AMERICA'
    AND POPULATION > 20000000
ORDER BY POPULACAO DESC;
