SELECT
    C.ID_CLIENTE,
    C.NOME,
    COUNT(P.ID_PEDIDO) AS QTD_PEDIDOS,
    COALESCE(SUM(P.VALOR), 0) AS TOTAL_GASTO
FROM CLIENTES C
LEFT JOIN PEDIDOS P
    ON C.ID_CLIENTE = P.ID_CLIENTE
GROUP BY C.ID_CLIENTE, C.NOME
ORDER BY C.NOME;
