SELECT
    C.ID_CLIENTE,
    C.NOME AS CLIENTE,
    C.CIDADE,
    P.ID_PEDIDO,
    P.PRODUTO,
    P.VALOR AS 'VALOR DO PEDIDO'
FROM CLIENTES C
LEFT JOIN PEDIDOS P
    ON C.ID_CLIENTE = P.ID_CLIENTE
ORDER BY P.ID_PEDIDO;
