SELECT
	C.CONTINENT AS CONTINENTE,
	COUNT(DISTINCT(C.NAME)) AS QTD_PAISES,
	SUM(CI.POPULATION) AS POPULACAO_TOTAL
FROM COUNTRY C
INNER JOIN CITY CI
ON C.CODE = CI.COUNTRYCODE
WHERE CI.NAME LIKE 'S%' AND CI.POPULATION > 200000
GROUP BY C.CONTINENT
HAVING SUM(CI.POPULATION) > 50000000
ORDER BY POPULACAO_TOTAL DESC;
