SELECT
	CI.NAME AS CIDADE,
	CI.POPULATION AS POPULACAO,
	C.NAME AS PAIS,
	C.CONTINENT AS CONTINENTE
FROM CITY CI
INNER JOIN COUNTRY C
ON CI.COUNTRYCODE = C.CODE
WHERE CI.POPULATION > (
	SELECT
		AVG(POPULATION)
	FROM CITY
)
AND C.CONTINENT = 'ASIA'
ORDER BY POPULACAO DESC
LIMIT 10;
