DELIMITER #

CREATE PROCEDURE LISTAR_CIDADES_POR_PAIS(IN P_PAIS VARCHAR(60))
BEGIN

	SELECT
		CI.NAME AS CIDADE,
		CI.POPULATION AS POPULACAO,
		C.NAME AS PAIS,
		C.CONTINENT AS CONTINENTE
	FROM CITY CI
	INNER JOIN COUNTRY C
	ON CI.COUNTRYCODE = C.CODE
	WHERE C.NAME = P_PAIS
	ORDER BY POPULACAO DESC
	LIMIT 15;
END #

DELIMITER ;

CALL LISTAR_CIDADES_POR_PAIS('BRAZIL');
