WITH CIDADES_GRANDES AS (
    SELECT
        COUNTRYCODE,
        NAME,
        POPULATION
    FROM CITY
    WHERE POPULATION > 1000000
)
SELECT
    C.NAME AS PAIS,
    C.CONTINENT AS CONTINENTE,
    COUNT(*) AS QTD_CIDADES_GRANDES,
    SUM(CG.POPULATION) AS POPULACAO_TOTAL
FROM CIDADES_GRANDES CG
INNER JOIN COUNTRY C
    ON CG.COUNTRYCODE = C.CODE
GROUP BY C.CODE, C.NAME, C.CONTINENT
HAVING COUNT(*) > 3
ORDER BY POPULACAO_TOTAL DESC
LIMIT 15;
