SELECT
    C.NAME AS PAIS,
    CI.NAME AS CIDADE,
    CI.POPULATION AS POPULACAO,
    'CIDADE GRANDE' AS TIPO_REGISTRO
FROM CITY CI
JOIN COUNTRY C
    ON CI.COUNTRYCODE = C.CODE
WHERE CI.POPULATION > 7000000

UNION

SELECT
    C.NAME AS PAIS,
    CI.NAME AS CIDADE,
    CI.POPULATION AS POPULACAO,
    'CAPITAL DE PAIS POPULOSO' AS TIPO_REGISTRO
FROM COUNTRY C
JOIN CITY CI
    ON C.CAPITAL = CI.ID
WHERE C.POPULATION > 50000000
ORDER BY POPULACAO DESC;
