DELIMITER # 

CREATE PROCEDURE LISTAR_PAISES_POR_CONTINENTE(IN P_CONTINENTE VARCHAR(30))
BEGIN

	SELECT
		NAME AS PAIS,
		CONTINENT AS CONTINENTE,
		POPULATION AS POPULACAO
	FROM COUNTRY
	WHERE CONTINENT = P_CONTINENTE
	ORDER BY POPULACAO DESC;

END #

DELIMITER ;

CALL LISTAR_PAISES_POR_CONTINENTE('SOUTH AMERICA');
