SELECT
    NAME AS PAIS,
    'PAIS' AS TIPO_REGISTRO,
    POPULATION AS POPULACAO
FROM COUNTRY
WHERE POPULATION > 100000000

UNION

SELECT
    NAME AS CIDADE,
    'CIDADE',
    POPULATION AS POPULACAO
FROM CITY
WHERE POPULATION > 8000000
ORDER BY POPULACAO DESC;
