DELIMITER #

CREATE PROCEDURE LISTAR_CIDADES_POR_POPULACAO(IN P_POPULACAO INT)
BEGIN

	SELECT
		CI.NAME AS CIDADE,
		CI.POPULATION AS POPULACAO,
		C.NAME AS PAIS
	FROM CITY CI
	INNER JOIN COUNTRY C
	ON CI.COUNTRYCODE = C.CODE
	WHERE CI.POPULATION > P_POPULACAO
	ORDER BY POPULACAO DESC
	LIMIT 10;

END #

DELIMITER ;

CALL LISTAR_CIDADES_POR_POPULACAO(50000);
