SELECT
    C.CONTINENT AS CONTINENTE,
    COUNT(DISTINCT C.CODE) AS QTD_PAISES,
    SUM(CI.POPULATION) AS POPULACAO_TOTAL,
    CASE
        WHEN SUM(CI.POPULATION) > 1000000000 THEN 'IMPACTO URBANO MUITO ALTO'
        WHEN SUM(CI.POPULATION) >= 500000000 AND SUM(CI.POPULATION) <= 1000000000 THEN 'IMPACTO URBANO ALTO'
        WHEN SUM(CI.POPULATION) >= 100000000 AND SUM(CI.POPULATION) < 500000000 THEN 'IMPACTO URBANO MÉDIO'
        ELSE 'IMPACTO URBANO BAIXO'
    END AS CLASSIFICACAO_IMPACTO_URBANO
FROM COUNTRY C
INNER JOIN CITY CI
    ON C.CODE = CI.COUNTRYCODE
WHERE CI.POPULATION > 300000
GROUP BY C.CONTINENT
ORDER BY POPULACAO_TOTAL DESC;
