SELECT
	C.NAME AS PAIS,
	C.CONTINENT AS CONTINENTE,
	COUNT(CI.ID) AS QTDE_CIDADES
FROM COUNTRY C
JOIN CITY CI
ON C.CODE = CI.COUNTRYCODE
WHERE EXISTS (SELECT 1
				  FROM CITY CI2
				  WHERE CI2.COUNTRYCODE = C.CODE AND
						    CI2.POPULATION > 5000000)
GROUP BY C.CODE, C.NAME, C.CONTINENT
HAVING COUNT(CI.ID) > 20
ORDER BY QTDE_CIDADES DESC
LIMIT 15;
