SELECT
	NAME AS PAIS,
	CONTINENT AS CONTINENTE,
	POPULATION AS POPULACAO
FROM COUNTRY
WHERE CODE IN (SELECT
	COUNTRYCODE
FROM CITY
WHERE POPULATION > 8000000) AND NAME LIKE '%A%'
ORDER BY POPULACAO DESC
LIMIT 10;
